### ISSUE TITLE
Features from hackathon integrated with demo backend

### ISSUE THREAD

**Issue by MateuszOlko** [spacy-pl/demo#13]
DOD:
- [x] as title says

**Comment by MateuszOlko** [comment]
Waiting for scrapped articles

**Comment by MateuszOlko** [comment]
Articles scraped: https://github.com/spacy-pl/utils/pull/58

**Comment by Gizzio** [comment]
Fix problem with degenerated articles and then merge

**Comment by Gizzio** [comment]
@kowaalczyk Check if everything works on windows 

https://github.com/spacy-pl/articles-demo

**Comment by kowaalczyk** [comment]
@Gizzio good job, everything is fine

**Comment by Gizzio** [comment]
@kowaalczyk check this commit and close

https://github.com/spacy-pl/articles-demo/commit/9562c090dae8066f3355000beaca717c210349ec
